//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereMobileServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentRow
    {
        public string ID { get; set; }
        public string ProductID { get; set; }
        public string LotID { get; set; }
        public double Quantity { get; set; }
        public decimal Sum { get; set; }
        public string DocumentID { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Lot Lot { get; set; }
        public virtual Product Product { get; set; }
    }
}
