//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereMobileServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WereMobileEntities : DbContext
    {
        public WereMobileEntities()
            : base("name=WereMobileEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode> Barcode { get; set; }
        public virtual DbSet<Contragent> Contragent { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentRow> DocumentRow { get; set; }
        public virtual DbSet<Lot> Lot { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
